//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnewinEventAspNetMvc5.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnewinEvent : DbContext
    {
        public KnewinEvent()
            : base("name=KnewinEvent")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALENDARIO> CALENDARIO { get; set; }
        public virtual DbSet<EQUIPE> EQUIPE { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<PRESENCA> PRESENCA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
