//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnewinEventAsp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALENDARIO()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int COD_CALENDARIO { get; set; }
        public string NOME { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<int> COD_EQUIPE { get; set; }
    
        public virtual EQUIPE EQUIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
