//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnewinEventAsp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.PRESENCA = new HashSet<PRESENCA>();
        }
    
        public int COD_EVENTO { get; set; }
        public string NOME { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<int> COD_CALENDARIO { get; set; }
    
        public virtual CALENDARIO CALENDARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESENCA> PRESENCA { get; set; }
    }
}
