//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnewinEventAsp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESENCA
    {
        public int COD_PRESENCA { get; set; }
        public int COD_EVENTO { get; set; }
        public int COD_USUARIO { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
