//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnewinEventAsp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PRESENCA = new HashSet<PRESENCA>();
        }
    
        public int COD_USUARIO { get; set; }
        public string NOME { get; set; }
        public string APELIDO { get; set; }
        public string SETOR { get; set; }
        public Nullable<decimal> DDD { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<int> COD_EQUIPE { get; set; }
    
        public virtual EQUIPE EQUIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESENCA> PRESENCA { get; set; }
    }
}
